### ISSUE TITLE
Step2 无法启动 REST Server

### ISSUE THREAD

**Issue by miuim** [Tom-Xu-CNXA/bikesharing#2]
我在使用 Fabric 1.2，Step1 运行没问题，升级到 Step2 后无法启动：
```
fabric@****:~/fabric-tools/bikesharing-network$ composer-rest-server --card admin@bikesharing-network --namespaces "never" --port 3100
Discovering types from business network definition ...
Discovering the Returning Transactions..
Discovered types from business network definition
Generating schemas for all types in business network definition ...
Registering named query: selectBikes
Registering named query: selectBikesByStatus
Registering named query: selectBikeRentTransaction
Generated schemas for all types in business network definition
Adding schemas for all types to Loopback ...
Swagger: skipping unknown type "Bike".
Swagger: skipping unknown type "BikeRentTransaction".
Swagger: skipping unknown type "Bike".
Swagger: skipping unknown type "BikeRentTransaction".
Swagger: skipping unknown type "Bike".
Swagger: skipping unknown type "BikeRentTransaction".
Swagger: skipping unknown type "Bike".
Swagger: skipping unknown type "BikeRentTransaction".
Swagger: skipping unknown type "Bike".
Swagger: skipping unknown type "BikeRentTransaction".
Swagger: skipping unknown type "BikeRentTransaction".
Swagger: skipping unknown type "BikeRentTransaction".
Swagger: skipping unknown type "BikeRentTransaction".
Swagger: skipping unknown type "BikeRentTransaction".
Swagger: skipping unknown type "BikeRentTransaction".
Added schemas for all types to Loopback
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3100
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1355:14)
    at listenInCluster (net.js:1396:12)
    at Server.listen (net.js:1480:7)
    at module.exports.promise.then.then (/home/fabric/.nvm/versions/node/v8.11.3/lib/node_modules/composer-rest-server/cli.js:135:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by tomxucnxa** [comment]
建议使用最新的Composer 试一下。
有消息说Composer 已经减少开发投入了。其实我挺喜欢它的概念。
